services:
  gateway:
    container_name: gateway-api-container
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - mongo_auth
      # - service3
    environment:
      - AUTH_API_URL=http://auth:3001 # URL сервиса аутентификации
      # - SERVICE3_URL=http://service3:3002 # URL нового сервиса
    networks:
      - app-network

  auth:
    container_name: auth-api-container
    build:
      context: ./login
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo_auth
    environment:
      - ENV=production
    networks:
      - app-network

  mongo_auth:
    container_name: mongo-auth-database
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: auth_db
    volumes:
      - mongo_data_auth:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data_auth:
